// app/components/AppDialog.vue
<template>
  <Teleport to="body">
    <Transition name="modal">
      <div v-if="state.open" class="modal-mask">
        <div class="modal-wrap dialog">
          <header class="modal-header">{{ state.title }}</header>
          <section class="modal-content dialog-content">
            <p class="dialog-message">{{ state.message }}</p>
            <input
              v-if="state.kind === 'prompt'"
              v-model="state.value"
              class="input dialog-input"
              autofocus
              @keyup.enter="submit"
            />
          </section>
          <footer class="modal-footer">
            <span class="btn" @click="cancel">取消</span>
            <span class="btn btn-primary" @click="submit">确定</span>
          </footer>
        </div>
      </div>
    </Transition>
  </Teleport>
</template>

<script setup lang="ts">
import { useDialog } from '~/composables/useDialog'

const { state, submit, cancel } = useDialog()
</script>

<style scoped>
.dialog {
  max-width: 360px;
}

.dialog-message {
  margin: 0;
  color: var(--text-color);
  word-break: break-all;
}

.dialog-input {
  width: 100%;
  margin-top: 8px;
}
</style>

// components/AppDialog.tsx
'use client'

import { useEffect, useState } from 'react'
import { createPortal } from 'react-dom'
import { useDialog } from '@/lib/client/dialog'
import { Transition } from './Transition'

/** 全局 confirm / prompt 对话框，替代原生 window.confirm / window.prompt */
export function AppDialog() {
  const { state, submit, cancel, setValue } = useDialog()
  const [mounted, setMounted] = useState(false)

  useEffect(() => {
    setMounted(true)
  }, [])

  if (!mounted) {
    return null
  }

  return createPortal(
    <Transition name="modal" show={state.open} duration={300}>
      <div className="modal-mask">
        <div className="modal-wrap dialog" role="dialog" aria-modal="true" aria-label={state.title}>
          <header className="modal-header">{state.title}</header>
          <section className="modal-content dialog-content">
            <p className="dialog-message">{state.message}</p>
            {state.kind === 'prompt' && (
              <input
                className="input dialog-input"
                autoFocus
                value={state.value}
                onChange={(event) => setValue(event.target.value)}
                onKeyDown={(event) => {
                  if (event.key === 'Enter') {
                    submit()
                  }
                }}
              />
            )}
          </section>
          <footer className="modal-footer">
            <button type="button" className="btn" onClick={cancel}>
              取消
            </button>
            <button type="button" className="btn btn-primary" onClick={submit}>
              确定
            </button>
          </footer>
        </div>
      </div>
    </Transition>,
    document.body
  )
}
